[project]
name = "nyc-housetype-predictor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Aarush Rawat", email = "rawataarush2005@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "joblib>=1.6.0",
    "pandas>=3.0.5",
    "scikit-learn==1.6.1",
]

[project.scripts]
nyc-housetype-predictor = "nyc_housetype_predictor:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
